# http://about.travis-ci.org/docs/user/ci-environment/
# http://about.travis-ci.org/docs/user/build-configuration/
# Travis uses Ubuntu 64 12.04
branches:
    only:
        - master

language: python
python:
    # - "2.6" enable it by specify packages in setup.py and test it
    - "2.7" 
compiler:
    - gcc

before_install:
    # - sudo apt-get update -qq
    - sudo apt-get install python-dev
    # ATLAS matrix library
    - sudo apt-get install libatlas3gf-base libblas-dev libatlas-dev libblas-dev libblas3gf
    # deps for pykaldi.audio FIXME REMOVE IT
    # - sudo apt-get install libasound2-dev
    - pushd /usr/include && sudo ln -s atlas/*.h . ; popd  # hack how to make available clapack.h FIXME failing cblas.h exists

install: 
    - pip install -q cython pystache pyyaml --use-mirrors
    # Openfst: building
    - pushd tools && make -j 4 openfst_tgt && popd
    # Configure with ATLAS (default)
    - pushd src && ./configure --atlas-root=/usr --shared && popd 
    - pushd src && make -j 4 && popd
    - pushd src/dec-wrap && make -j 4 && popd

script:
    # the PATH is necessary for fstcompilation TODO get rid of it
    - pushd src/dec-wrap && PATH=../../tools/openfst/bin:$PATH make -j 4 test && popd  
    - pushd src/pykaldi && make test && popd
