# http://about.travis-ci.org/docs/user/ci-environment/
# http://about.travis-ci.org/docs/user/build-configuration/
# Travis uses Ubuntu 64 12.04

language: python
python:
    # - "2.6" enable it by specify packages in setup.py and test it
    - "2.7" 
compiler:
    - gcc

install: 
    # cffi deps
    - sudo apt-get install python-dev libffi-dev  
    - pip install -q cffi --use-mirrors
    # ATLAS matrix library
    - sudo apt-get install libatlas3gf-base
    # OpenBLAS long lasting alternative with build
    # - pushd tools && sudo apt-get install gfortran && make openblas 2> /dev/null ; popd  # make opeblas returns 2
    # Openfst
    - pushd tools && make openfst_tgt && popd
    - pushd src && ./configure  --openblas-root=`pwd`/../tools/OpenBLAS/install --fst-root=`pwd`/../tools/openfst --shared && popd 
    - pushd src && make depend 2>/dev/null >/dev/null && popd
    - pushd src && make && popd

script:          
    - pushd src && make test && popd
    - pushd src/dec-wrap && make depend && make && make test && popd
    - pushd src/pykaldi && python setup.py nosetests  # currently it will fail because of audio -> need get rid of makefile
