# http://about.travis-ci.org/docs/user/ci-environment/
# http://about.travis-ci.org/docs/user/build-configuration/
# Travis uses Ubuntu 64 12.04

language: python
python:
    # - "2.6" enable it by specify packages in setup.py and test it
    - "2.7" 
compiler:
    - gcc

install: 
    # cffi deps
    - sudo apt-get install python-dev libffi-dev  
    - pip install -q cffi --use-mirrors
    # # openblas matrix library deps
    # - sudo apt-get install libopenblas-dev liblapacke-dev
    # # little fix for openblas
    # - pushd /usr/lib && sudo ln -s /usr/lib/openblas-base/libopenblas.so && popd
    # long lasting alternative
    - pushd tools && make openblas 2> /dev/null && popd
    # openfst
    - pushd tools && make openfst_tgt && popd
    - pushd src && ./configure  --openblas-root=`pwd`/../tools/OpenBLAS/install --fst-root=`pwd`/../tools/openfst --shared && popd 
    - pushd src && make depend 2>/dev/null >/dev/null && popd
    - pushd src && make && popd

script:          
    - pushd src && make test && popd
    - pushd src/dec-wrap && make depend && make && make test && popd
    - pushd src/pykaldi && make test 
    # - pushd src/pykaldi nosetest
    # - pushd src/pykaldi/binutils nosetest
