# http://about.travis-ci.org/docs/user/ci-environment/
# http://about.travis-ci.org/docs/user/build-configuration/
# Travis uses Ubuntu 64 12.04

language: python
python:
    # - "2.6" enable it by specify packages in setup.py and test it
    - "2.7" 
compiler:
    - gcc

install: 
    - sudo apt-get install python-dev libffi-dev  # cffi deps
    - pip install -q cffi --use-mirrors
    - sudo apt-get install gfortran  # openblas compilation dep
    - pushd tools && make openblas && popd
    # - sudo apt-get install openblas # does not work
    # - pushd src && ./configure  --openblas-root=/usr --fst-root=`pwd`/../tools/openfst --shared && make depend && popd
    - pushd tools && make openfst_tgt && popd
    - pushd src && ./configure  --openblas-root=`pwd`/../tools/OpenBLAS/install --fst-root=`pwd`/../tools/openfst --shared && popd 
    - pushd src && make depend && popd
    - pushd src && make && popd


script:          
    - pushd src/dec-wrap && make depend && make && make test && popd
    - pushd src/pykaldi && make test 
    # - pushd src/pykaldi nosetest
    # - pushd src/pykaldi/binutils nosetest
