# http://about.travis-ci.org/docs/user/ci-environment/
# http://about.travis-ci.org/docs/user/build-configuration/


language: python
python:
    # - "2.6"   # disabled 2.6 because of cython problems
    - "2.7"

# disable clang because of cython problems
# matrix:
#     include:
#         - compiler: gcc
#           env: GCC=4.7
#         - compiler: clang


before_install:
    # Update to g++-GCC e.g. 4.7 on Ubuntu 12.04
    - export GCC=4.7; sudo apt-get update -qq && sudo apt-get install -y python-software-properties && sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y && sudo apt-get update -qq && sudo apt-get install -y g++-$GCC gcc-$GCC && export CXX=g++-$GCC && export CC=gcc-$GCC
    - sudo apt-get install -y build-essential libatlas-base-dev python-dev python-pip git wget zip
    - pip install -r pykaldi/pykaldi-requirements.txt
    - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]] ; then pip install unittest2 ordereddict argparse ; fi
    - sudo curl -sL https://raw.githubusercontent.com/travis-ci/artifacts/master/install | bash

install:
    - make -j 4 pyfst/fst/_fst.so; make -j 4 onl-rec/onl-rec.a

script:
    - make -j 1 test

after_success:
    # with more paralelization for deploy it fails for lack of memory
    - if [[ $TRAVIS_BRANCH == 'alex-pykaldi' && $TRAVIS_PULL_REQUEST == 'false' && $TRAVIS_PYTHON_VERSION == '2.7' ]] ; then make -j 1 deploy && echo "Deployed package pripared" && curl --ftp-create-dirs -T pykaldi*.zip -u $JOB_USER:$JOB_PASS ftp://$JOB_ADDRESS && echo "Uploaded ok" ; fi
