# http://about.travis-ci.org/docs/user/ci-environment/
# http://about.travis-ci.org/docs/user/build-configuration/
# Travis uses Ubuntu 64 12.04
branches:
    except:
        - svn-mirror 

# cache: 
#     - apt

# settings according http://blog.travis-ci.com/2012-12-18-travis-artifacts/#How-to-use%3F
# LZ owns the access keys
env:
 global:
   - "ARTIFACTS_AWS_REGION=us-east-1"
   - "ARTIFACTS_S3_BUCKET=ufal-dsg"
   - secure: "WBfd5tHszuzZxvI0slNPyRObYgMCi6pm07OEecuOfVtgLdMQWRaaRAxChM+m8gMTkV44TuTY4ony1XVIItc+8jcXOL+DhIbj8dt+kpd927QYjiQVQf0vhVBQpIJIyYr40tPeezr7/vBbktl/c4cVF7Vd/k1SVX5/dnLtt4s05JE=" 
   - secure: "TC4N7oiqeGmy2f9GfoZoZrTxDGEJLIDH3L4YoZQ7tl7Pu93SRv6Yo0L2j2Jn8aziM4XqOSEJNwP/F1o3/n8n7+LhPsyRd4FjHEIQomGlgR9im/zRJ6BHn6nChYldq/t4x4LcIVwdSRyLRykgXYRTr2xLOELBeVO9HUxChMYTpFo="


language: python
python:
    # - "2.6"   # disabling 2.6 because of cython problems
    - "2.7"
compiler:
    - gcc

before_install:
    # Update to g++ 4.7
    - sudo apt-get update && sudo apt-get install -y python-software-properties
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y && sudo apt-get update -qq && sudo apt-get install -y g++-4.7 gcc-4.7 && sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.7 50 && sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.7 80 && gcc --version && g++ --version
    # ATLAS matrix library
    # - sudo apt-get install -y libatlas3gf-base libblas-dev libatlas-dev libblas-dev libblas3gf
    - sudo apt-get install -y build-essential libatlas-base-dev python-dev python-pip git wget zip
    - pushd pykaldi && pip install -q -r pykaldi-requirements.txt ; popd 
    - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]] ; then pip install unittest2 ordereddict argparse ; fi
    - gem install travis-artifacts

script:
    - make -j 4 && make -j 2 deploy && travis-artifacts upload --path pykaldi*.zip --target-path pykaldi/pykaldi-travis_${TRAVIS_PYTHON_VERSION}.tar.gz
