# http://about.travis-ci.org/docs/user/ci-environment/
# http://about.travis-ci.org/docs/user/build-configuration/
# Travis uses Ubuntu 64 12.04
branches:
    only:
        - master


# settings according http://blog.travis-ci.com/2012-12-18-travis-artifacts/#How-to-use%3F
# LZ owns the access keys
env:
 global:
   - "ARTIFACTS_AWS_REGION=us-east-1"
   - "ARTIFACTS_S3_BUCKET=ufal-dsg"
   - secure: "WBfd5tHszuzZxvI0slNPyRObYgMCi6pm07OEecuOfVtgLdMQWRaaRAxChM+m8gMTkV44TuTY4ony1XVIItc+8jcXOL+DhIbj8dt+kpd927QYjiQVQf0vhVBQpIJIyYr40tPeezr7/vBbktl/c4cVF7Vd/k1SVX5/dnLtt4s05JE=" 
   - secure: "TC4N7oiqeGmy2f9GfoZoZrTxDGEJLIDH3L4YoZQ7tl7Pu93SRv6Yo0L2j2Jn8aziM4XqOSEJNwP/F1o3/n8n7+LhPsyRd4FjHEIQomGlgR9im/zRJ6BHn6nChYldq/t4x4LcIVwdSRyLRykgXYRTr2xLOELBeVO9HUxChMYTpFo="

language: python
python:
    - "2.6"
    - "2.7"
compiler:
    - gcc

before_install:
    - sudo apt-get update -qq
    # Update to g++ 4.8
    - sudo apt-get install g++-4.8 && sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
    - sudo apt-get install python-dev
    # ATLAS matrix library
    - sudo apt-get install libatlas3gf-base libblas-dev libatlas-dev libblas-dev libblas3gf

install:
    - pip install -q cython pystache pyyaml --use-mirrors
    - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]] ; then pip install --use-mirrors unittest2 ordereddict argparse ; fi
    # Openfst: skip building Openfst ~ 30 min
    # # - pushd tools && make -j 4 openfst_tgt && popd
    # Openfst: download
    - ls -al
    - pushd tools && wget https://s3-eu-west-1.amazonaws.com/ufal-dsg/openfst/travis-openfst.tar.gz -O travis-openfst.tar.gz && tar zxvf travis-openfst.tar.gz && ln -s travis-openfst openfst && popd
    # hack how to make available clapack.h
    - pushd tools && make -j 4 atlas && popd
    # Configure with ATLAS (default)
    - pushd src && ./configure --shared && popd
    - pushd src && make -j 4 && popd
    - pushd src/onl-rec && make -j 4 && popd

script:
    - pushd src/onl-rec && make -j 4 test ; RET=$?; popd ; (exit $RET)
    - pushd src/pykaldi && make -j 4 test ; RET=$? ; popd ; (exit $RET)

after_success: # and this only on success
    - tar cvzf pykaldi.tar.gz src/pykaldi
    - travis-artifacts upload --path pykaldi_src_pykaldi.tar.gz --target-path pykaldi/pykaldi_src_pykaldi.tar.gz
    # - travis-artifacts upload --path pykaldi_src_pykaldi.tar.gz --target-path artifacts/$TRAVIS_BUILD_ID/$TRAVIS_JOB_ID
